let dataBase = [
    
{
    id: 1,
    name: "Liam",
    age: 25, 
    gender: "Male",
    crossfitExersicePreferd: "Toes to bar", 
    crossfitExersiceWorst: "Thruster",
},
{
    id: 2,
    name: "Camille",
    age: 23, 
    gender: "Female",
    crossfitExersicePreferd: "Handstand pushup", 
    crossfitExersiceWorst: "Push Jerk",
},
{
    id: 3,
    name: "Noel",
    age: 22, 
    gender: "Male",
    crossfitExersicePreferd: "Thruster", 
    crossfitExersiceWorst: "Kettelbell Swing",
},
{
    id: 4,
    name: "Celine",
    age: 21, 
    gender: "Female",
    crossfitExersicePreferd: "Snatch", 
    crossfitExersiceWorst: "Kettelbell Swing",
},
{
    id: 5,
    name: "Filip",
    age: 26, 
    gender: "Male",
    crossfitExersicePreferd: "Snatch", 
    crossfitExersiceWorst: "Toes to bar",
},
{
    id: 6,
    name: "Henrik",
    age: 26, 
    gender: "Male",
    crossfitExersicePreferd: "Toes to bar", 
    crossfitExersiceWorst: "Snatch",
},
{
    id: 7,
    name: "Aude",
    age: 31, 
    gender: "Female",
    crossfitExersicePreferd: "Snatch", 
    crossfitExersiceWorst: "Wall Ball",
},
{
    id: 8,
    name: "Katty",
    age: 31, 
    gender: "Female",
    crossfitExersicePreferd: "Over head squats", 
    crossfitExersiceWorst: "Push Jerk",
},
{
    id: 9,
    name: "Ella",
    age: 33, 
    gender: "Female",
    crossfitExersicePreferd: "Thruster", 
    crossfitExersiceWorst: "Shoulder Press",
},
{
    id: 10,
    name: "Andreas",
    age: 20, 
    gender: "Male",
    crossfitExersicePreferd: "Push Jerk", 
    crossfitExersiceWorst: "Wall Ball",
},

]